version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-data-factory-guy
    versions:
    - 3.9.8
  - dependency-name: ember-concurrency
    versions:
    - 1.3.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
